#!/bin/bash

export LANG=en_US.UTF-8
export DEV_HOME=$HOME/dev

if [[ -x "$(command -v nvim)" ]]; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
export VISUAL="EDITOR"

## JAVA
for _j in /opt/homebrew/opt/openjdk@21 \
          /home/linuxbrew/.linuxbrew/opt/openjdk@21 \
          /usr/lib/jvm/java-21-openjdk-amd64 \
          /usr/lib/jvm/java-21-openjdk \
          /usr/lib/jvm/temurin-21; do
  [[ -d "$_j" ]] && { export JAVA_HOME="$_j"; break; }
done
unset _j
[[ -n "${JAVA_HOME:-}" ]] && export PATH="$JAVA_HOME/bin:$PATH"
