#!/bin/bash

export LANG=en_US.UTF-8
export DEV_HOME=$HOME/dev

if [[ -x "$(command -v nvim)" ]]; then
  export EDITOR=nvim
else
  export EDITOR=vim
fi
export VISUAL="EDITOR"

## JAVA
export JAVA_HOME="/opt/homebrew/opt/openjdk@21"
export PATH="$JAVA_HOME/bin:$PATH"
