#!/bin/bash

# OMZ
alias omzr="omz reload"

# GIT
alias lg="lazygit"
alias push="git push"
alias pushf="git push -f"
alias pull="git pull"
alias status="git status"

# TMUX
alias tls="tmux ls"
alias ta="tmux a -t"
alias tn="tmux new"

# MISC
alias ll="ls -la --color=auto"
alias fzfc="fzf --exact < <(find . -maxdepth 1 | sed -e 's/.\/\(.*\)/\1/g')"
alias cdc='cd $(find . -type d -maxdepth 1 | sed -r "s/(\.\/)|(\.)//g" | fzf)' 
alias cm='chezmoi'
alias sail='sh $([ -f sail ] && echo sail || echo vendor/bin/sail)'
alias nv='nvim'
