#!/bin/bash

if command -v flutter &> /dev/null
then
    FLUTTER_COMPLETION_FILE_PATH="$ZSH_CUSTOMS_PATH/completions/flutter_completion.sh"
	if [[ -e "$FLUTTER_COMPLETION_FILE_PATH" ]]; then
		source $FLUTTER_COMPLETION_FILE_PATH
	fi
fi

### fx completion ###
if command -v fx &> /dev/null
then
  source <(fx --comp zsh)
fi
### end fx completion ###

### ngrok completion
if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi
### end ngrok completion

if command -v exercism &> /dev/null
then
	EXERCISM_COMPLETION_FILE_PATH="$ZSH_CUSTOMS_PATH/completions/exercism_autocomplete.sh"
	if [[ -e "$EXERCISM_COMPLETION_FILE_PATH" ]]; then
		source $EXERCISM_COMPLETION_FILE_PATH
	fi
fi

