#!/bin/bash

### HELIX
function hxf() {
	file=$(fzf --exact --preview 'bat --style=numbers --color=always {}')
	
	if [[ -n "$file" ]]; then
		hx $file
	fi
}

function cdd() {
	if [[ -n "$DEV_HOME" && -d "$DEV_HOME" ]]; then
		cd $DEV_HOME/$(ls -d $DEV_HOME/*/ | sed -r "s^$DEV_HOME/(.*)/^\1^g" | fzf --exact)
	fi
}
