[[language]]
name = "php"
auto-format = true

[[language]]
name = "html"
auto-format = true

[[language]]
name = "go"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
