set -g prefix C-b
bind-key C-b send-prefix

set -g mouse on

set -g renumber-windows on

bind-key j join-pane

# Utilise le même cwd que le pane actif lors des splits
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Tu peux aussi forcer le comportement par défaut
set-option -g default-command ""
set-option -g default-shell $SHELL

set-option -g history-limit 100000

# Configuration requise pour image.nvim
set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on
